import { Link } from 'react-router-dom';
import { ArrowRight, Boxes, Route, Warehouse } from 'lucide-react';
import InquiryForm from '@/components/InquiryForm';
import { logisticsFamilyPath, logisticsPagePath, type LogisticsFamily, type LogisticsSeoPage } from '@/data/logisticsSeo';

const hubCopy = {
  logistics: {
    eyebrow: 'Logistics learning guide',
    title: 'Logistics Courses, Careers and Supply Chain Learning Guides',
    intro: 'Use this independent resource hub to compare logistics subjects, study formats, career preparation, admission questions and location-focused learning options before choosing a diploma pathway.',
    sections: [
      ['How to use this logistics guide', 'Logistics connects sourcing, purchasing, inbound movement, storage, inventory, order fulfilment, transport and customer service. This hub organises those subjects around the decisions learners actually need to make. Start with the operating area that matches your goal, compare the related guides, and then review the complete diploma page for current delivery and admission information. A useful comparison considers syllabus depth, guided practice, assessment, trainer feedback and the evidence a learner can produce at the end.'],
      ['Build a complete supply-chain view', 'A logistics learner should understand how one decision affects the rest of the chain. Buying additional stock may improve availability while increasing storage cost and ageing risk. Faster transport may protect a delivery promise while changing the total landed cost. Practical study therefore uses connected scenarios, records and performance measures. Learners trace material and information from supplier to customer, identify handovers, investigate exceptions and explain the trade-offs behind a recommendation.'],
      ['Choose learning by career objective', 'Course selection becomes clearer when it begins with a target responsibility. Procurement support requires supplier records and purchase coordination. Inventory work needs disciplined transaction control and stock analysis. Transport coordination involves shipment planning, documentation and delivery follow-up. Operations analysis adds spreadsheets, measures and improvement reporting. Job titles differ between employers, so candidates should compare current descriptions and build transferable evidence rather than relying on a title alone.'],
      ['Evaluate practical course quality', 'Ask how many hours involve supervised exercises, whether projects use realistic records, how work is reviewed and what must be completed for certification. Confirm the precise duration, mode, fee inclusions, eligibility and batch schedule in writing. Placement assistance should mean preparation and access to suitable opportunities; employer selection remains independent. The strongest option is the one that fits the learner’s starting level and provides enough practice to explain processes confidently.'],
      ['Create portfolio evidence', 'A useful logistics portfolio can include a process map, inventory analysis, shipment comparison, exception report, dashboard and improvement proposal. Each item should state the problem, source information, assumptions, method, result and limits. Confidential data must be removed. This structure helps a learner demonstrate accuracy and reasoning during assessment or interview discussion instead of presenting unsupported claims.'],
      ['Next step for logistics training', 'Browse the focused guides below for fees, admissions, online study, certification, careers, internships and local searches. When ready, open the diploma pathway to review the complete course direction. Request the latest syllabus and schedule because operational examples and batch availability can change. Compare the response with your weekly study time, travel needs and intended role before enrolling.'],
    ],
  },
  warehouse: {
    eyebrow: 'Warehouse operations resource',
    title: 'Warehouse Management, Inventory and Operations Learning Guides',
    intro: 'Explore warehouse-focused guidance covering receiving, storage, stock accuracy, picking, dispatch, safety, systems, certification and career preparation before selecting formal training.',
    sections: [
      ['Start with the warehouse workflow', 'Warehouse work begins before goods reach a storage location. Receiving teams check quantity, condition and documents; put-away decisions protect space and accessibility; replenishment supports picking; packing and dispatch controls protect order accuracy. This hub groups learning guides around that operating sequence. Readers can examine a specific question and then move to the complete diploma page when they need current course and admission details.'],
      ['Strengthen inventory accuracy', 'Inventory control depends on correct identification, location discipline and timely transactions. Training should explain cycle counting, discrepancy investigation, ABC classification, reorder thinking, ageing and exception reporting. A practical exercise compares physical stock with the system record, follows the transaction history and documents the cause before a correction is approved. This habit protects availability, reporting quality and customer service.'],
      ['Improve fulfilment and space use', 'Layout and slotting influence travel, congestion, safety and picking time. Learners should be able to map a flow, distinguish fast and slow movement, review replenishment points and measure the effect of a proposed change. Fulfilment practice covers order release, picking methods, verification, packing, labelling, staging and handover. Returns require their own inspection and disposition controls so that unsuitable stock does not quietly re-enter availability.'],
      ['Treat safety as an operating control', 'Housekeeping, marked routes, load awareness, equipment rules and incident reporting belong inside daily operations. A credible warehouse course connects safety to each process rather than limiting it to a short introductory topic. Learners identify hazards, choose controls, assign responsibility and define evidence that the control is working. Employer and legal requirements must always be confirmed for the actual workplace.'],
      ['Use systems and measures responsibly', 'Barcode concepts, warehouse systems and spreadsheets improve traceability only when source data is dependable. Useful measures include receiving turnaround, inventory accuracy, picking productivity, dispatch accuracy, damage and on-time completion. Learners should know the definition and source behind every figure. A dashboard becomes meaningful when it leads to investigation and action, not when it only presents attractive charts.'],
      ['Plan warehouse career preparation', 'Entry and progression opportunities may include warehouse associate, inventory controller, dispatch executive, team coordinator and operations analyst. Candidates benefit from documenting practical exercises and learning to explain discrepancies, priorities, safety decisions and improvements. Browse the focused pages below, compare their guidance, and request the latest diploma syllabus, schedule, eligibility and fee details before making an admission decision.'],
    ],
  },
} as const;

export default function LogisticsGuideHub({ family, pages }: { family: LogisticsFamily; pages: LogisticsSeoPage[] }) {
  const copy = hubCopy[family];
  const image = family === 'warehouse' ? '/images/warehouse-inventory-course-hero.webp' : '/images/logistics-supply-chain-course-hero.webp';
  return <main>
    <section className="relative flex min-h-[560px] items-center overflow-hidden pt-28 text-white"><img src={image} alt={`${copy.title} overview`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/75"/><div className="container relative mx-auto grid gap-10 px-4 py-14 lg:grid-cols-[1.15fr_.85fr]"><div><p className="font-semibold text-orange-300">{copy.eyebrow}</p><h1 className="mt-4 text-4xl font-bold md:text-6xl">{copy.title}</h1><p className="mt-5 text-lg leading-8 text-gray-200">{copy.intro}</p><Link to={logisticsFamilyPath(family)} className="mt-7 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 font-semibold">View diploma pathway <ArrowRight className="h-4 w-4"/></Link></div><div className="rounded-2xl bg-background p-6 text-foreground"><h2 className="text-2xl font-bold">Ask for course guidance</h2><p className="my-3 text-sm text-muted-foreground">Request the current syllabus, schedule, eligibility and fee details.</p><InquiryForm stacked preselectedCourse="management"/></div></div></section>
    <section className="section-padding"><article className="container mx-auto max-w-4xl space-y-10 px-4">{copy.sections.map(([heading, text], index) => <section key={heading}><h2 className="flex items-center gap-3 text-2xl font-bold md:text-3xl">{index === 0 ? family === 'warehouse' ? <Warehouse className="text-primary"/> : <Route className="text-primary"/> : index === 2 ? <Boxes className="text-primary"/> : null}{heading}</h2><p className="mt-4 leading-8 text-muted-foreground">{text}</p></section>)}</article></section>
    <section className="section-padding bg-muted/30"><div className="container mx-auto px-4"><h2 className="text-3xl font-bold">Browse focused {family === 'warehouse' ? 'warehouse' : 'logistics'} guides</h2><p className="mt-3 max-w-3xl text-muted-foreground">These pages answer distinct course, career, fee, location and admission searches. The diploma page remains the complete programme landing page.</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{pages.slice(0, 36).map((page) => <Link key={page.slug} to={logisticsPagePath(page)} className="rounded-xl border bg-background p-5 hover-lift"><span className="text-xs font-semibold uppercase text-primary">{page.location || page.intent}</span><h3 className="mt-2 font-bold">{page.title}</h3></Link>)}</div></div></section>
  </main>;
}
